App\Entity\Construction\Project:
    type: entity
    table: project
    indexes:
        created_idx:
            columns: [ created ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        created:
            column: created
            type: datetime
            nullable: false
    manyToOne:
        vico:
            targetEntity: App\Entity\Construction\Vico
            inversedBy: projects
            joinColumn:
                name: vico_id
                referencedColumnName: id
            nullable: true
    oneToMany:
        reviews:
            targetEntity: App\Entity\Review\Review
            mappedBy: project
            cascade: [ "persist" ]
    lifecycleCallbacks: {  }
