App\Entity\ReviewConstruction\ReviewConstructionItem:
    type: entity
    table: review_construction_item
    indexes:
        created_idx:
            columns: [ created ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: false
        page:
            type: integer
            length: 12
            nullable: false
        created:
            column: created
            type: datetime
            nullable: false
    manyToOne:
        reviewConstructionItemType:
            targetEntity: App\Entity\ReviewConstruction\ReviewConstructionItemType
            inversedBy: reviewConstructionItems
            joinColumn:
                name: parent_type_id
                referencedColumnName: id
    oneToMany:
        reviewItems:
            targetEntity: App\Entity\Review\ReviewItem
            mappedBy: reviewConstruction
            cascade: [ "persist" ]
    lifecycleCallbacks: {  }
