services:
    app.listener.review.inserted:
        class: App\EventListener\ReviewInsertedNotifier
        tags:
            - { name: kernel.event_listener, event: app.review.inserted, method: notify }
        autowire: true
        public: true
